server:
  port: 9090
Scheduler:
  cron: 0 0/2 0 * * *
ecommerce:
  urls:
    shopClues: http://a73b24953b5ba4cb6aeb518ad5c35411-897494200.ap-south-1.elb.amazonaws.com:8080/products #backendloadbalancers
    shopcluesazure: http://52.140.5.133:8080/products #backendazureloadbalancers
