server:
  port: 9090
Scheduler:
  cron: 0 0/2 0 * * *
ecommerce:
  urls:
    shopClues: http://aa446e220e3364ababde070c574bbdb3-1627272937.ap-south-1.elb.amazonaws.com:8080/products #backendloadbalancers
    shopWise: http://acdc997d4e62844e5b18a5cab25be6a5-1921957856.ap-south-1.elb.amazonaws.com:9091/products
