server:
  port: 9090
Scheduler:
  cron: 0 0/2 0 * * *
ecommerce:
  urls:
    shopClues: http://a845b65c48bd041a1a8d11323cfaed57-1505025973.ap-south-1.elb.amazonaws.com:8080/products #backendloadbalancers
    shopWise: http://af6eaf03f67054c84a76faa9927487b7-2093146003.ap-south-1.elb.amazonaws.com:9091/products
